#!/usr/bin/env bash
# tools/wasm/build.sh — CSR wasm ビルド手順（イシュー #411 実装計画 §2.3）。
#
# 役割: `templates/app/wasm`（独立ワークスペース、glue クレート `app-csr-wasm`）
# を wasm32-unknown-unknown へビルドし、wasm-bindgen CLI で
# `static/wasm/fandhe_frontend_wasm_client.js` / `fandhe_frontend_wasm_client_bg.wasm` を生成する。
# `static/embed.html` の `import ... from "./wasm/fandhe_frontend_wasm_client.js"`
# （無改変）と整合させるため `--out-name fandhe_frontend_wasm_client` を固定する。
#
# 前提（fail-closed。黙示的にスキップしない、`.claude/rules/ci.md`）:
#   - rustup ターゲット wasm32-unknown-unknown が追加済みであること
#   - wasm-bindgen-cli が PATH 上にあり、`wasm/Cargo.lock` が解決した
#     wasm-bindgen クレートのバージョンと完全一致すること
#     （`dist-server/build.rs::expected_wasm_bindgen_version` と同一の
#     契約。バージョン不一致は wasm-bindgen 自体の既知の制約により実行時に
#     壊れるため、ここで停止する）。
#
# プロジェクトルート（`fw new` が生成したディレクトリ、この build.sh の
# 2 階層上）から実行する固定コマンド列。ユーザー入力を受け取らず、
# シェル変数はすべてクォートする（`.claude/rules/security.md` A01/A03）。
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
project_root="$(cd -- "${script_dir}/../.." >/dev/null 2>&1 && pwd)"
wasm_manifest="${project_root}/wasm/Cargo.toml"
wasm_lock="${project_root}/wasm/Cargo.lock"
out_dir="${project_root}/static/wasm"
# `CARGO_TARGET_DIR` が呼び出し側（CI のフィクスチャ専用ディレクトリ指定等、
# `.claude/rules/ci.md` の共有 CARGO_TARGET_DIR 対策）で設定されている場合は
# それを尊重してアーティファクトパスを解決する。未設定時は cargo の既定挙動
# （`${wasm_manifest}` と同階層の `target/`）に合わせて `wasm/target` を使う。
target_dir="${CARGO_TARGET_DIR:-${project_root}/wasm/target}"

if [ ! -f "${wasm_manifest}" ]; then
  echo "error: ${wasm_manifest} not found. Run this script from a project generated by \`fw new --template app\`." >&2
  exit 1
fi

# --- (a) 前提ツールの存在チェック ---
if ! command -v rustup >/dev/null 2>&1; then
  echo "error: rustup not found on PATH. Install rustup: https://rustup.rs/" >&2
  exit 1
fi

if ! rustup target list --installed | grep -qx "wasm32-unknown-unknown"; then
  echo "error: rustup target \`wasm32-unknown-unknown\` is not installed." >&2
  echo "fix: rustup target add wasm32-unknown-unknown" >&2
  exit 1
fi

if ! command -v wasm-bindgen >/dev/null 2>&1; then
  echo "error: wasm-bindgen-cli not found on PATH." >&2
  echo "fix: cargo install wasm-bindgen-cli --version <version-matching-wasm/Cargo.lock> --locked" >&2
  exit 1
fi

# --- (b) wasm-bindgen クレートのバージョンと CLI のバージョンの完全一致検証 ---
# `wasm/Cargo.lock` から動的に読むため、バージョン pin 箇所を新設しない
# （`.claude/rules/ci.md` の pin ドリフト検知運用と同じ考え方）。
expected_version="$(awk '
  /^\[\[package\]\]$/ { in_pkg = 1; name = ""; next }
  in_pkg && /^name = "wasm-bindgen"$/ { name = "wasm-bindgen"; next }
  in_pkg && name == "wasm-bindgen" && /^version = / {
    gsub(/^version = "|"$/, "");
    print;
    exit
  }
  /^\[\[package\]\]$/ { next }
' "${wasm_lock}")"

if [ -z "${expected_version}" ]; then
  echo "error: could not determine the required wasm-bindgen-cli version from ${wasm_lock}" >&2
  echo "fix: verify wasm/Cargo.lock contains a [[package]] entry named \"wasm-bindgen\"" >&2
  exit 1
fi

installed_version="$(wasm-bindgen --version | awk '{print $2}')"

if [ "${installed_version}" != "${expected_version}" ]; then
  echo "error: wasm-bindgen-cli version mismatch: wasm/Cargo.lock resolves wasm-bindgen ${expected_version}, but \`wasm-bindgen --version\` reports ${installed_version}." >&2
  echo "fix: cargo install wasm-bindgen-cli --version ${expected_version} --locked" >&2
  exit 1
fi

# --- (c) wasm32 ビルド ---
cargo build \
  --manifest-path "${wasm_manifest}" \
  --target wasm32-unknown-unknown \
  --release

wasm_artifact="${target_dir}/wasm32-unknown-unknown/release/app_csr_wasm.wasm"
if [ ! -f "${wasm_artifact}" ]; then
  echo "error: expected build artifact not found: ${wasm_artifact}" >&2
  exit 1
fi

# --- (d) wasm-bindgen 後処理 ---
mkdir -p "${out_dir}"
wasm-bindgen --target web --out-dir "${out_dir}" --out-name fandhe_frontend_wasm_client "${wasm_artifact}"

echo "wasm build complete: ${out_dir}/fandhe_frontend_wasm_client.js, ${out_dir}/fandhe_frontend_wasm_client_bg.wasm"
